### ISSUE TITLE
Ship a 1.0 release

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/bare-metal#22]
Part of https://github.com/rust-embedded/wg/issues/383

Blockers:

* [x] remove const-fn now it's in Rust
* [x] specify our MSRV
* [x] Review and merge https://github.com/rust-embedded/bare-metal/pull/20 to fix https://github.com/rust-embedded/bare-metal/issues/7
* [ ] Review against https://rust-lang.github.io/api-guidelines/ – happening in https://github.com/rust-embedded/bare-metal/issues/26
* [x] ~Mutex is not safe on multi-core systems - https://github.com/rust-embedded/bare-metal/issues/12~
* [x] Should `Peripheral` be removed?
* [x] What to do with the `Nr` trait? (it's gone)

**Comment by jonas-schievink** [comment]
Some simple improvements to be made before 1.0:
* Remove the `const-fn` feature, and the build.rs logic related to `const fn` support
* Review and merge https://github.com/rust-embedded/bare-metal/pull/20 to fix https://github.com/rust-embedded/bare-metal/issues/7

Other blockers:
* Resolve https://github.com/rust-embedded/bare-metal/issues/12 via https://github.com/rust-embedded/wg/pull/388

Unresolved questions:
* Where is `bare_metal::Peripheral` used? Does it pull its weight? Needs more documentation.
* Same goes for `bare_metal::Nr`. Would it be better to move it outside this crate? Also: Why return `u8`?

**Comment by rubberduck203** [comment]
As soon as I find the markdown version of the API checklist, I’m going to create a tracking issue for that work so items can be checked off as they’re reviewed.

**Comment by rubberduck203** [comment]
Found it. Will open the tracking issue when time allows. https://github.com/rust-lang/api-guidelines/blob/master/src/checklist.md

**Comment by therealprof** [comment]
As agreed in the 2020-03-10 meeting we're taking off the `Mutex` from the 1.0 blocker list. We're aiming to have the new `Mutex` based on `mutex-trait` implemented by the arch crates instead.

**Comment by luojia65** [comment]
Maybe `Nr` can be used as a parameter to configure vendor specific interrupt controller. However in this way `Nr::nr` should not always return a `u8` (there could be more than 256 interrupts). Maybe necessary to provide as `Nr { type Count; fn nr(&self) -> Self::Count }` (still working on it to adapt to Bumblebee's ECLIC controller)

**Comment by jonas-schievink** [comment]
IMO `Nr` logically belongs in architecture-specific core crates like cortex-m or cortex-m-rt.

We should check what uses it, and whether the users would see any benefit of having a traits that's shared between architectures. Maybe come up with potential use cases.

**Comment by thejpster** [comment]
Ticked MSRV, as it's in the README.

**Comment by adamgreig** [comment]
Closed by #35.
